### PR TITLE
Shikkic/GitHub commit search by date

### PR DESCRIPTION
**Pull request by Shikkic**
This creates an interface for looking up commit SHAs for a packageModel by a timestamp range.
 
Still pending a light review, DMY

### CODE REVIEW

**Comment by skeswa** [comment]
We need to add an encrypted script to the repo that adds github tokens to the database.

**Comment by Shikkic** [comment]
Is this a blocker or just an annoyance? I can make one tonight

**Comment by skeswa** [comment]
Just an annoyance

**Comment by Shikkic** [comment]
I'm going to merge this in for now so you have an interface to use for getting commit SHA if you want to. I actually have some more changes to implement but I'll write that up in a separate PR and I'll create a new task/epic for it

**Pull request merged**
